spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/imonitdb"
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    hibernate.ddl-auto: update
    show-sql: true